title: Digital Image Processing for Remote Sensing
description: Fundamentals of Digital Image Processing & applications with Google Earth Engine
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
github:
  is_project_page: false
